  
version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
    build:
    commands:
      - cd client
      - npm run build
      - cd..